---
- hosts: database
  become: yes
  vars:
    mysql_root_password: root
  tasks:
  - name: Install MySQL
    apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
    sudo: yes
    with_items:
    - python-mysqldb
    - mysql-server
    - mysql-client
  - name: Start the MySQL service
    sudo: yes
    service:
      name: mysql
      state: started
      enabled: true
  - name: update mysql root password for all root accounts
    sudo: yes
    mysql_user:
      name: vels
      host: "{{ item }}"
      password: "{{ mysql_root_password }}"
      login_user: vels
      login_password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost
#databases:
#  testingadb:
#    name: test
#    user: test
#    userhost: localhost
#    password: "{{ mysql_root_password }}"
